W18ADATE-271 refactor: add run_step helper to simplify step execution and error handling

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -13,66 +13,40 @@ if [ "$branch" = "main" ]; then
   exit 1
 fi
 
-##############################
-########## FRONTEND ##########
-##############################
-
-run_frontend_checks() {
-    echo "⚙️ Running frontend checks"
-    cd "$FRONTEND_DIR" || exit 1
-
-    # Linting
-    echo "🔍 Frontend - Lint"
-    npx lint-staged || {
-        echo "❌ Frontend - Lint failed"
-        exit 1
-    }
-
-    # Building
-    echo "🧱 Frontend - Build"
-    npm run build || {
-        echo "❌ Frontend - Build failed"
-        exit 1
-    }
-
-    cd ..
+run_step() {
+  desc="$1"
+  shift
+  echo "$desc"
+  "$@" || {
+    echo "❌ $desc failed ❌"
+    exit 1
+  }
 }
 
-#############################
-########## BACKEND ##########
-#############################
+run_frontend_checks() {
+    echo "⚙️ Frontend checks"
+    pushd "$FRONTEND_DIR" > /dev/null || exit 1
+
+    run_step "Frontend - Lint" npx lint-staged
+    run_step "Frontend - Build" npm run build
+
+    popd > /dev/null
+}
 
 run_backend_checks() {
-    echo "⚙️ Running backend checks"
-    cd "$BACKEND_DIR" || exit 1
+    echo "⚙️ Backend checks"
+    pushd "$BACKEND_DIR" > /dev/null || exit 1
 
-    # Building
-    echo "🧱 Backend - Build"
-    dotnet build --nologo || {
-        echo "❌ Backend - Build failed"
-        exit 1
-    }
+    run_step "Backend - Build" dotnet build --nologo
+    run_step "Backend - Format" dotnet format
+    run_step "Backend - Format (Verify no Changes)" dotnet format --verify-no-changes --verbosity quiet
+    run_step "Backend - Test" dotnet test
 
-    # Linting
-    echo "🔍 Backend - Lint"
-    dotnet format
-    dotnet format --verify-no-changes --verbosity quiet || {
-        echo "❌ Backend - Lint failed"
-        exit 1
-    }
-
-    # Testing
-    echo "🧪 Backend - Test"
-    dotnet test || {
-        echo "❌ Backend - Test failed"
-        exit 1
-    }
-
-    cd ..
+    popd > /dev/null
 }
 
 staged_files=$(git diff --cached --name-only --diff-filter=ACM)
-printf "📄 Staged files:\n$staged_files\n"
+printf "📄 Staged Files:\n$staged_files\n"
 
 if echo "$staged_files" | grep -q "^$FRONTEND_DIR/"; then
     run_frontend_checks
@@ -81,6 +55,5 @@ fi
 if echo "$staged_files" | grep -q "^$BACKEND_DIR/"; then
     run_backend_checks
 fi
-
 
 echo "✅ All pre-commit checks passed!"
